- hosts: all
  vars_files:
    - vars/all.yml
  tasks:
    - name: import role
      import_role: 
        name: k8s-multimaster
      become: true
      register: status
    - name: introducing pause for the cluster to be ready
      pause:
        seconds: 60
      tags: setup
      become: true